<#
.SYNOPSIS
     Create OU & Move Meeting Room Objects

.DESCRIPTION
     Script will create a new OU and move Exchange Meeting Room Objects to the new OU.
	 
.Inputs

.Outputs
     N/A

.Link

.NOTES
     Generated On:  05/12/2018
     Last Modified: 05/12/2018
     Generated By: Edward Martin (EM)

     ==============================
     Start Changelog
     ==============================
     V1.0.0 EM
     -    Created initial script
     
     ==============================
     End Changelog
     ==============================
#>

####################################################
## Enter Log File Output Location in $LogFilePath ##
####################################################

$LogFilePath = ""

################
## New AD OUs ##
################

$ADOUs = @("")

####################
## Destination OU ##
####################

$DestinationOU = ""

##########################################################
## Script Actions Below. Do not modify below this line. ##
##########################################################

Function Add-LogEntry
{
     Param([ValidateSet("Error", "Info", "Warning")][String]$LogLevel,[String]$LogEntry)
     $UTCTime = Get-Date ((Get-Date).ToUniversalTime()) -Format "HH:mm"
     $LocalTime = Get-Date -Format "HH:mm"
     If ((New-TimeSpan -Start $UTCTime -End $LocalTime) -GT 0)
     {
           $UTCTimeDifferencePosNeg = "+"
     }
     $UTCTimeDifferenceHours = (New-TimeSpan -Start $UTCTime -End $LocalTime).Hours.ToString("00")
     $UTCTimeDifferenceMinutes = ((New-TimeSpan -Start $UTCTime -End $LocalTime).Minutes.ToString("`:00")).Replace("-","")
     $UTCTimeDifferenceHoursMinutes = "$UTCTimeDifferencePosNeg$UTCTimeDifferenceHours$UTCTimeDifferenceMinutes"
     $LogEntryDateTime = "D" + (Get-Date -Format s)
     "UTC$UTCTimeDifferenceHoursMinutes$LogEntryDateTime - $LogLevel - $LogEntry" | Out-File -FilePath $Logfile -append
}

Import-Module ActiveDirectory

$LogFile = "$($LogFilePath)\$(Get-Date -UFormat "%Y%m%d").txt"

$MeetingRooms = Get-ADUser -Filter * -Properties * | Where {$_.msExchResourceDisplay -eq "Room"}

Add-LogEntry -LogLevel Info -LogEntry "##########################################"
Add-LogEntry -LogLevel Info -LogEntry "############ Log File Start ##############"
Add-LogEntry -LogLevel Info -LogEntry "##########################################"
Add-LogEntry -LogLevel Info -LogEntry "Found - $($MeetingRooms.count) Meeting Rooms Objects"
Add-LogEntry -LogLevel Info -LogEntry "Destination OU - $DestinationOU"

ForEach ($ADOU in $ADOUs) {
	New-ADOrganizationalUnit -Name "" -Path $ADOU
	Add-LogEntry -LogLevel Info -LogEntry "Created - $ADOU"
	}
	
ForEach ($MeetingRoom in $MeetingRooms) {
	Move-ADObject $MeetingRoom -Target $DestinationOU
	Add-LogEntry -LogLevel -Info -LogEntry "Moved - $($MeetingRoom.SamAccountName) ($($MeetingRoom.Name))"
	}

Add-LogEntry -LogLevel Info -LogEntry "##########################################"
Add-LogEntry -LogLevel Info -LogEntry "############## Log File End ##############"
Add-LogEntry -LogLevel Info -LogEntry "##########################################"
